import type { AnalysisResults, BeamModel } from '../solver/types';

/** Convert an array of {x, value} points into CSV text. */
export function diagramToCSV(label: string, points: { x: number; value: number }[]): string {
  const header = `x,${label}\n`;
  const rows = points.map((p) => `${p.x.toFixed(6)},${p.value.toFixed(6)}`).join('\n');
  return header + rows + '\n';
}

/** Combine all diagrams into one CSV. */
export function resultsToCSV(results: AnalysisResults): string {
  const lines: string[] = [];
  lines.push('# Beam Calculator Results — SI units');
  lines.push('# Reactions');
  lines.push('supportId,position(m),Fy(kN),Fx(kN),Mz(kN·m)');
  for (const r of results.reactions) {
    lines.push(`${r.supportId},${r.position},${r.Fy.toFixed(4)},${(r.Fx ?? 0).toFixed(4)},${(r.Mz ?? 0).toFixed(4)}`);
  }
  lines.push('# Summary');
  lines.push(`maxShear_kN,${results.maxShear.toFixed(4)}`);
  lines.push(`maxMoment_kNm,${results.maxMoment.toFixed(4)}`);
  lines.push(`minMoment_kNm,${results.minMoment.toFixed(4)}`);
  lines.push(`maxDeflection_mm,${results.maxDeflection.toFixed(4)}`);
  if (results.maxBendingStress !== undefined)
    lines.push(`maxBendingStress_MPa,${results.maxBendingStress.toFixed(4)}`);
  lines.push('# Shear Force Diagram\nx(m),V(kN)');
  results.sfd.forEach((p) => lines.push(`${p.x.toFixed(4)},${p.value.toFixed(4)}`));
  lines.push('# Bending Moment Diagram\nx(m),M(kN·m)');
  results.bmd.forEach((p) => lines.push(`${p.x.toFixed(4)},${p.value.toFixed(4)}`));
  lines.push('# Deflection\nx(m),v(mm)');
  results.deflection.forEach((p) => lines.push(`${p.x.toFixed(4)},${p.value.toFixed(4)}`));
  return lines.join('\n');
}

/** Trigger a file download in the browser. */
export function downloadFile(filename: string, content: string, mime = 'text/plain'): void {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  setTimeout(() => {
    URL.revokeObjectURL(url);
    a.remove();
  }, 0);
}

/** Build a printable HTML report and open the print dialog (PDF). */
export function exportPDF(model: BeamModel, results: AnalysisResults): void {
  const win = window.open('', '_blank');
  if (!win) return;
  const reactionRows = results.reactions
    .map(
      (r) =>
        `<tr><td>${r.supportId}</td><td>${r.position.toFixed(3)}</td><td>${r.Fy.toFixed(3)}</td><td>${(r.Fx ?? 0).toFixed(3)}</td><td>${(r.Mz ?? 0).toFixed(3)}</td></tr>`,
    )
    .join('');
  win.document.write(`
    <html><head><title>Beam Analysis Report</title>
    <style>
      body { font-family: system-ui, sans-serif; padding: 24px; color: #111; }
      h1 { margin: 0 0 8px; }
      h2 { margin: 24px 0 8px; border-bottom: 1px solid #aaa; padding-bottom: 4px; }
      table { border-collapse: collapse; margin: 8px 0; width: 100%; }
      td, th { border: 1px solid #999; padding: 4px 8px; text-align: right; font-family: ui-monospace, monospace; font-size: 12px; }
      th { background: #f0f0f0; }
      .summary { display: grid; grid-template-columns: repeat(2, 1fr); gap: 4px 16px; font-family: ui-monospace, monospace; font-size: 13px; }
    </style></head><body>
      <h1>Beam Analysis Report</h1>
      <div>Generated: ${new Date().toLocaleString()}</div>
      <h2>Beam Configuration</h2>
      <div class="summary">
        <div>Length: ${model.length} m</div>
        <div>Material: ${model.material.name} (E = ${model.material.E} MPa)</div>
        <div>Section: ${model.section.name ?? 'custom'} (I = ${model.section.I.toExponential(3)} m⁴)</div>
        <div>Supports: ${model.supports.length}</div>
        <div>Loads: ${model.loads.length}</div>
        <div>Determinacy: ${results.determinacy.classification}</div>
      </div>
      <h2>Reactions</h2>
      <table>
        <tr><th>Support</th><th>x (m)</th><th>Fy (kN)</th><th>Fx (kN)</th><th>Mz (kN·m)</th></tr>
        ${reactionRows}
      </table>
      <h2>Result Summary</h2>
      <div class="summary">
        <div>Max Shear: ${results.maxShear.toFixed(3)} kN</div>
        <div>Max Moment: ${results.maxMoment.toFixed(3)} kN·m</div>
        <div>Min Moment: ${results.minMoment.toFixed(3)} kN·m</div>
        <div>Max Deflection: ${results.maxDeflection.toFixed(3)} mm</div>
        ${
          results.maxBendingStress !== undefined
            ? `<div>Max Bending Stress: ${results.maxBendingStress.toFixed(2)} MPa</div>`
            : ''
        }
        ${
          results.utilization !== undefined
            ? `<div>Utilization (σ/fy): ${(results.utilization * 100).toFixed(1)} %</div>`
            : ''
        }
      </div>
      <p style="margin-top:24px;color:#555;font-size:11px">
        Generated by the Beam Calculator. Verify all design values independently.
      </p>
    </body></html>
  `);
  win.document.close();
  setTimeout(() => {
    win.print();
  }, 300);
}
